# Generated by Django 3.2.8 on 2021-10-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brl1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='satya',
        ),
    ]
